language: python

dist: jammy

matrix:
  fast_finish: true
  include:
    - python: '3.5'
    - python: '3.6'
    - python: '3.7'
    - python: '3.8'
    - python: '3.9'
    - python: '3.10'
    - python: 'nightly'
    - python: 'pypy3'
install:
  - pip install coveralls pytest
script:
  - coverage run -m pytest tests/
  - coverage combine
after_success:
  - coveralls
