language: python

dist: focal

matrix:
  fast_finish: true
  include:
    - python: '3.5'
    - python: '3.6'
    - python: '3.7'
    - python: '3.8'
    - python: '3.8'
      dist:  jammy
    - python: '3.9'
      dist:  jammy
    - python: '3.10'
      dist:  jammy
    - python: 'nightly'
      dist:  jammy
    - python: 'pypy3'
      dist:  jammy
install:
  - git clone https://github.com/docopt/docopt && pip3 install -e docopt
  - pip3 install --upgrade setuptools wheel pytest docopt coverage coveralls
script:
  - coverage run -m pytest tests/
  - coverage combine
after_success:
  - coveralls
